package rules
import com.example.rule.drools.User            // 导入类
dialect  "mvel"
rule "age"                                      // 规则名，唯一
    no-loop true
    lock-on-active true
    salience 1
    when
        $user : User(age<15 || age>60)     //规则的条件部分
    then
        System.out.println("年龄不符合要求！");
        $user.setName("年龄不符合要求");
        update($user);
        System.out.println($user);
end